AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack simples - EC2 + Security Group + VPC"

Resources:
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "MyVPC"

  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security Group para EC2"
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-051f8a213df8bc089"
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref MySecurityGroup
      SubnetId: !Ref MyVPC